compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmScopes:
  grafana-ml:
    npmRegistryServer: https://us-npm.pkg.dev/grafanalabs-dev/ml-npm-dev/
    npmAlwaysAuth: true
